version: '3'
services:

  nextcloud:
    image: nextcloud:stable
    depends_on:
      - mysql
      - redis
    env_file: config/nextcloud.env
    environment:
      NEXTCLOUD_DATA_DIR: /vol/data
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${MYSQL_USER:-nextcloud}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
      TZ: ${TZ:-UTC}
    ports:
      - ${NEXTCLOUD_PORT}:80
    tmpfs: /tmp
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - nextcloud-html:/var/www/html
      - ${NEXTCLOUD_CONFIG_PATH:-nextcloud-config}:/var/www/html/config
      - ${NEXTCLOUD_DATA_PATH:-nextcloud-data}:/vol/data
      - ./volumes/mysql/conf.d:/etc/mysql/conf.d
    labels:
      com.centurylinklabs.watchtower.scope: nextcloud-compose
    restart: unless-stopped

  cron:
    image: nextcloud:stable
    depends_on:
      - mysql
      - redis
    env_file: config/nextcloud.env
    environment:
      NEXTCLOUD_DATA_DIR: /vol/data
      TZ: ${TZ:-UTC}
    tmpfs: /tmp
    volumes:
      - nextcloud-html:/var/www/html
      - ${NEXTCLOUD_CONFIG_PATH:-nextcloud-config}:/var/www/html/config
      - ${NEXTCLOUD_DATA_PATH:-nextcloud-data}:/vol/data
    entrypoint: /cron.sh
    labels:
      com.centurylinklabs.watchtower.scope: nextcloud-compose
    restart: unless-stopped
  
  mysql:
    image: mysql:8.0
    ports:
      - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${MYSQL_USER:-nextcloud}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - nextcloud-mysql:/var/lib/mysql
    labels:
      com.centurylinklabs.watchtower.scope: nextcloud-compose
    restart: unless-stopped

  redis:
    image: redis:6.0
    labels:
      com.centurylinklabs.watchtower.scope: nextcloud-compose
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    env_file: config/watchtower.env
    environment:
      WATCHTOWER_SCOPE: nextcloud-compose
      TZ: ${TZ:-UTC}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.scope: nextcloud-compose
    restart: unless-stopped

volumes:
  nextcloud-html: {}
  nextcloud-config: {}
  nextcloud-data: {}
  nextcloud-mysql: {}
